name = "Squawky's Cobblemon Fun!"
author = "Squawkykaka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43c3bfea6bc61c0ef261360841bc8f39bd856c6773ada8c3eee1047d4daab981"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
